### ISSUE TITLE
Grey area doesn't clear

### ISSUE THREAD

**Issue by towerofnix** [robinp7720/WebBloks#3]
So when I drag a block from the right (white) to the left (grey) it ends up being really weird! :P

![lolwut](https://cloud.githubusercontent.com/assets/9948030/8997188/ef3d40ee-36f4-11e5-8f7e-58be18861ebc.png)

**Comment by robinp7720** [comment]
I fixed that already :p

**Comment by towerofnix** [comment]
Ah okay. :P
